CREATE TABLE IF NOT EXISTS Customer(
  id SERIAL PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  groupName VARCHAR(255) NOT NULL,
  companyName VARCHAR(255) NOT NULL,
  innerName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CustomerOrder(
  id SERIAL PRIMARY KEY,
  customerId DECIMAL NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  customerInnerId VARCHAR(255) DEFAULT NULL,
  sequenceName VARCHAR(255) NOT NULL,
  sequence VARCHAR(255) NOT NULL,
  editedSequence VARCHAR(255) DEFAULT NULL,
  scale INTEGER NOT NULL,
  purification VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  orderDate TIMESTAMP DEFAULT current_timestamp NOT NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'Megrendelt',
  price INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS LaborUser(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Purification(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderType(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderStatus(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);